version: '3.5'

services:
  server:
    container_name: server
    build: api.js
    expose:
      - '3001'
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
    command: node api.js
    ports:
      - '3001:3001'

  portfolio-app:
    container_name: portfolio-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
